version: '3.8'
services:
  grafana:
    image: bitnami/grafana:8.5.6-debian-11-r1
    container_name: grafana
    hostname: grafana
    networks:
    - net_aurora_qa
    restart: unless-stopped
    volumes:
    - ./grafana/conf/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
    - ./grafana/conf/defaults.ini:/opt/bitnami/grafana/conf/defaults.ini
    - ./grafana/conf/datasources/:/opt/bitnami/grafana/conf/provisioning/datasources/
    - ./grafana/conf/dashboards/:/opt/bitnami/grafana/public/dashboards/
    ports:
    - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "5"
  prometheus:
    image: bitnami/prometheus:2.36.1-debian-11-r4
    container_name: prometheus
    hostname: prometheus
    networks:
    - net_aurora_qa
    restart: unless-stopped
    volumes:
    - ./prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/prometheus.yml
    - ./prometheus/data:/opt/bitnami/prometheus/data
    command:
    - '--storage.tsdb.retention=200h'
    expose:
    - 9090
    ports:
    - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "5"
  nginxsrv:
    image: nginx:alpine
    container_name: nginxsrv
    hostname: nginxsrv
    networks: 
    - net_aurora_qa
    restart: unless-stopped
    volumes:
      - ./nginxsrv/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./results/:/www-data/public/test/results/
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "5"
  jmetersrv:
    hostname: jmetersrv
    container_name: jmetersrv
    build:
      context: ./jmetersrv/
      args:
        JMETER_VERSION: ${JMETER_VERSION:-5.4.3}
        NODE_VERSION: ${NODE_VERSION:-16.14.2}
      dockerfile: Dockerfile
    networks:
    - net_aurora_qa
    restart: "no"
    volumes:
      - ./results/:/opt/aurora/test-suite/results/
      - ./tests/:/opt/aurora/test-suite/tests/
      - ./jmetersrv/conf/:/opt/aurora/test-suite/conf/
      - ./jmetersrv/lib/:/opt/aurora/test-suite/lib/
    expose:
    - 9270
    ports:
    - "9270:9270"
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "5"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    sysctls:
      net.ipv4.ip_local_port_range: 10000 65000
      net.ipv4.tcp_rmem: 87380 16777216 33554432
      net.ipv4.tcp_wmem: 87380 16777216 33554432
      net.ipv4.tcp_max_syn_backlog: 30000
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_synack_retries: 2
networks:
  net_aurora_qa: