global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
      monitor: 'jmeter-tests'

scrape_configs:
  - job_name: 'jmeter'
    scrape_interval: 15s
    static_configs:
      - targets: ['jmetersrv:9270']
