{
 "title": "Aurora-QA",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1s,5s,15m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Transaction Test1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(BatchRequestTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(TransactionTest1_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(TransactionTest1_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(TransactionTest1_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Batch Request Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(BatchRequestTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(BatchRequestTest_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "sum(BatchRequestTest_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(BatchRequestTest_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Request Object Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestObjectTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(RequestObjectTest_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "sum(BatchRequestTest_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestObjectTest_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Request Parameter Test 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestParameterTest1_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(RequestParameterTest1_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 31 },
   "targets": [
    {
     "expr": "sum(RequestParameterTest1_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestParameterTest1_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Request Parameter Test 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestParameterTest2_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(RequestParameterTest2_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 41 },
   "targets": [
    {
     "expr": "sum(RequestParameterTest2_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(RequestParameterTest2_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Response Time Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ResponseTimeTest_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 51 },
   "targets": [
    {
     "expr": "sum(ResponseTimeTest_failure_total) by (label)"
    }
   ]
  },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ResponseTimeTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ResponseTimeTest_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Edge To Relayer Latency Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(EdgeToRelayerLatencyTest_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(EdgeToRelayerLatencyTest_success_ratio_total[1s]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(EdgeToRelayerLatencyTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(EdgeToRelayerLatencyTest_success_ratio_failure{})"
    }
   ]
  },
  { "title": "Basic Load Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(BasicLoadTest_response_time{}) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(BasicLoadTest_success_ratio_total[1s]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Total Request ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(BasicLoadTest_success_ratio_total{})"
    }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(BasicLoadTest_success_ratio_failure{})"
    }
   ]
  }
 ]
}